name: CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Build release file
        run: GOARCH=386 go build -o http-run-code
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            http-run-code
